version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demodb
  mentions:
    build: ./MentionsService
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      APP_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/demodb
      KAFKA_BROKER: kafka:9092
  twitter:
    build: ./TwitterService
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092




